pipeline {
    agent any
    environment {
        def BUILDVERSION = sh(script: "echo `date +%d%m%H%M`", returnStdout: true).trim()
    }
        stages {
            stage('package') {
                steps {
                    sh './spring/user/mvnw -f ./spring/user -Dmaven.test.skip=true package'
                }
            }
            stage('build') {
                steps {
                    sh 'docker build --no-cache -t java-user:${BUILDVERSION} ./spring/user'
                }
            }
            stage('tag') {
                steps {
                    sh 'docker tag java-user:${BUILDVERSION} localhost:5000/java-user:${BUILDVERSION}'
                }
            }
            stage('push') {
                steps {
                    sh 'docker push localhost:5000/java-user:${BUILDVERSION}'
                }
            }
        }
}
