version: '3.3'

networks:
  chartissimo_bridge:
    ipam:
      config:
        - subnet: 172.19.1.0/24

volumes:
  mariadatabase:
  mongodatabase:
  mongoconfigdb:

services:
  api:
    container_name: chartapi
    build: ./api
    image: chart_api:latest
    user: node
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    networks:
       chartissimo_bridge:
          ipv4_address: 172.19.1.5
    volumes:
      - ./api/src:/home/node/app/src/
      - ./api/.env:/home/node/app/.env
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - "mariadatabase"
      - "mongodatabase"


  authentication:
    container_name: chartauth
    build: ./auth
    image: chart_auth:latest
    user: node
    networks:
       chartissimo_bridge:
          ipv4_address: 172.19.1.6
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./auth/src:/home/node/app/src/
      - ./auth/.env:/home/node/app/.env
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - "mongodatabase"

  frontend:
    container_name: chartfront
    build: ./client
    image: chart_frontend:latest
    user: node
    stdin_open: true
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./client/public/:/home/node/app/public
      - ./client/src/:/home/node/app/src
      - ./client/.env:/home/node/app/.env
    networks:
      - chartissimo_bridge
    restart: always
    ports:
      - "80:3000"
      - "3000:3000"
    command: npm run start

  mariadatabase:
    image: mariadb:10.4
    # image: mysql:5.6
    container_name: chartmaria
    user: mysql
    command: mysqld --character-set-server=utf8 --wait-timeout=31536000
    networks:
      - chartissimo_bridge
    volumes:
      - mariadatabase:/var/lib/mysql
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d/
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PW}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PW}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DB}

  mongodatabase: 
    image: mongo:4.4.4
    container_name: chartmongo
    networks: 
      - chartissimo_bridge
    volumes: 
      - mongodatabase:/data/db
      - mongoconfigdb:/data/configdb
      - ./mongodb/dump:/dump
    restart: always
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGODB_ROOT_PASSWORD}
