pipeline {
    agent any
    environment {
        def BUILDVERSION = sh(script: "echo `date +%d%m%H%M`", returnStdout: true).trim()
    }
        stages {
            stage('package') {
                steps {
                    sh './spring/gateway/mvnw -f ./spring/gateway -Dmaven.test.skip=true package'
                }
            }
            stage('build') {
                steps {
                    sh 'docker build --no-cache -t java-gateway:${BUILDVERSION} ./spring/gateway'
                }
            }
            stage('tag') {
                steps {
                    sh 'docker tag java-gateway:${BUILDVERSION} localhost:5000/java-gateway:${BUILDVERSION}'
                }
            }
            stage('push') {
                steps {
                    sh 'docker push localhost:5000/java-gateway:${BUILDVERSION}'
                }
            }
        }
}
